feat: 투표하기 구현
mafia-together/frontend pull request #21
Opened 2024-04-29 09:55 UTC by cheonjiyun

1. 클릭했을 때 투표하기 서버에 전송
2. 빨간색이 제대로 안보이던 css 오류 수정

close #19

2024-04-29 11:37 UTC, kpeel5839 requested changes
처음 리뷰네요!

한번 확인해 볼 만한 것들만 댓글 남겼어요

확인해 주시고 댓글 남겨주시면 감사할 것 같습니다.

2024-04-29 11:37 UTC, kpeel5839 commented on src/components/modal/Vote.tsx
> +        // ]);
Mock 데이터인가요?

그렇다면, 따로 상수로 빼놓는 것도 괜찮을 것 같아요. 아니라면 저희는 깃허브를 사용하고 있으니까 이전 커밋에서 찾는 방법도 있을 것 같고요!

사용하지 않는 코드는 주석보다는 지우는 것이 나을 것 같습니다! 지윤님은 어떻게 생각하시나요?

2024-04-29 11:37 UTC, kpeel5839 commented on src/components/modal/Vote.tsx
> +        });
오우 Array.from이라는 문법을 처음봐서 이해하는데 좀 걸렸네요, 검색해서 보니까 정해둔 length만큼 화살표 함수로 반환한 객체를 채워서 반환하는 것이었네요.

깔끔한 코드인 것 같습니다!

아직 에러를 통합적으로 처리하는 부분이 없다면, 여기서 catch를 통해서 콘솔을 남기는 방법도 좋은 방법일 것 같아요! 아직 개발 과정 중에 있으니 이런 에러로그 같은 것들을 바로 바로 볼 수 있게 해놓는다면 효율을 높일 수 있을 것 같습니다!

2024-04-29 11:37 UTC, kpeel5839 commented on src/components/modal/Vote.tsx
> +                    onChange={() => setVote(0, "")}
제가 아직 도메인을 정확히는 파악하고 있지 못해서, voteTarget === 0 을 메서드로 뺴주어 의미를 부여하거나, 혹은 0이라는 숫자와 ""을 상수로 빼주어서 의미를 부여하는 방법도 좋을 것 같아요!

지윤짱은 어떻게 생각하세요?

2024-04-29 11:37 UTC, kpeel5839 commented on src/components/player/PlayerVote.tsx
> +    player: { name: string; isAlive: boolean; role: string | null };
오 undefined는 허용하지 않으려는 의도였나요?

2024-04-29 11:37 UTC, kpeel5839 commented on src/pages/CreateRoom.tsx
> +            axiosInstance.post("/room", roleCount).then((response) => {
이거 잘못수정된 것일까요? Restful 기본원칙에 따라 복수형을 사용하기 때문에 rooms가 맞을 것 같아요.
![image](https://github.com/mafia-together/frontend/assets/89840550/c15ba7b8-172f-4bb9-991e-1827acedeac0)
실제로 위위와 같이 저희 API명세에 rooms라고 나와있어서요. 제가 잘못이해하고 있는 것이라면 피드백 부탁드릴게요!

2024-04-29 11:48 UTC, cheonjiyun commented on src/components/modal/Vote.tsx
> +        // ]);
Mock데이터 맞습니다! 아하 나중에 어디에 목데이터를 넣어야할지 헷갈릴까봐 주석처리한거였지만, 재연님 말씀해도 커밋에서 찾을 수 있으니까 지우는게 좋을 거 같네요!
지우고 다시 커밋하겠습니당

2024-04-29 12:33 UTC, cheonjiyun commented on src/components/modal/Vote.tsx
> +                    onChange={() => setVote(0, "")}
아하 voteTarget는 지금 사용자가 투표를 한 사람의 인덱스 번호를 담고 있습니다.
그래서 각 플레이어 컴포넌트는 `checked={voteTarget === index}` 로 플레이어 인덱스와 지금 투표를 하고 있는 사람의 인덱스를 비교해서 같다면 빨간색을 표시하고 있는데 **,기권은 인덱스가 없어서 0으로 부여한 것 뿐입니다!** ""는 이름 api에서 기권이라는 표시입니다,

저는 기권영역에만 쓰고 있어서 상수로 빼면 오히려 더 복잡해지지 않을까 생각합니당.
하지만 재연님처럼 처음보는 사람을 파악이 힘들 수 있다는 점은 이해가 갑니다. 조금 코드를 추가하더라고 상수로 빼는 게 좋을까요?

어떤게 중요하다고 판단하시나용?

2024-04-29 12:34 UTC, cheonjiyun commented on src/components/player/PlayerVote.tsx
> +    player: { name: string; isAlive: boolean; role: string | null };
넵 undefined이 들어오는 경우는 없어서 제거했습니다

2024-04-29 12:35 UTC, cheonjiyun commented on src/pages/CreateRoom.tsx
> +            axiosInstance.post("/room", roleCount).then((response) => {
아 이건 아까 api테스트해본다고 바꾼건데 투표하기 구현과 맞지 않은 커밋을 올려버렸군요...

아까 /room 으로 반영되어있다고 해서 변경했습니다

2024-04-29 12:37 UTC, cheonjiyun commented on src/components/modal/Vote.tsx
> +        });
오우 죄송해요 Array.from 이거는 WaitingRoom.tsx (대기방) 에서 비어있는 컴포넌트(대기중인 사람 컴포넌트)를 만들기 위해 썼던건데, 무지성으로 복붙해버렸네요.. 지웠는데 지금은 괜찮나요?

재연님 말씀대로 에러 처리도 필요하겠네요! try catch 감싼 영역이 괜찮은지 봐주시면 감사하겠습니당

2024-04-29 21:56 UTC, kpeel5839 commented on src/components/modal/Vote.tsx
> +                    onChange={() => setVote(0, "")}
> 저는 기권영역에만 쓰고 있어서 상수로 빼면 오히려 더 복잡해지지 않을까 생각합니당.

만일 복잡해지는 이유가 코드를 추가함으로써 코드양이 많아지기 때문이라면 추가하는 것이 좋을 것 같아요.
말씀해주셨던 것처럼 voteTarget===index는 투표를 하고 있는 사람의 인덱스를 비교하는 로직이고, **0**은 기권을 나타내기 위해 인덱스를 이와 같이 표현한 것이고, ""는 정확하게 기권이라는 의미를 가지고 있죠.

저는 이거를 상수화한다면 무조건 이해를 도울 수 있다고 보기 때문에, 단순 코드가 추가되는 것만이 문제라면 추가해야한다고 봅니다!

2024-04-29 21:57 UTC, kpeel5839 commented on src/pages/CreateRoom.tsx
> +            axiosInstance.post("/room", roleCount).then((response) => {
아, 현재는 room으로 반영이 되어있나보군요!

2024-04-29 22:01 UTC, kpeel5839 approved these changes
고생하셨습니다 지윤님!
많이 배워갑니다. 앞으로도 많은 가르침 주세요
코멘트는 추가적으로 하나 남겼습니다. 질문한 것이니 편하게 답변해주시면 감사할 것 같습니다.

2024-04-29 22:01 UTC, kpeel5839 commented on src/components/modal/Vote.tsx
> +        }
현재 이 방식이 exception이 발생했을 때 예외를 잡아주는지 확실하게 모르겠네요.

```ts
axiosInstance.get("/rooms/info").then((response) => {
    // 플레이어 배열
    setPlayers([...response.data.players]);
}).catch((error)=>console.log(...));
```
다음과 같이 이렇게 promise?를 반환하는 경우에, 다음과 같이 잡아줘야 하지 않나요? 이 부분은 정확하지 않아서 여쭤봅니다

2024-05-03 12:17 UTC, cheonjiyun commented on src/components/modal/Vote.tsx
> +                    onChange={() => setVote(0, "")}
아하 그렇군요! 동의합니다. 추가하겠습니다!

2024-05-03 12:20 UTC, cheonjiyun commented on src/components/modal/Vote.tsx
> +        }
아 그러네요..!
그런데 미리 정의하는 걸로 바꾸면 예외처리를 인터셉트에서하면 되는거 맞죠..?

2024-05-03 23:22 UTC, kpeel5839 commented on src/components/modal/Vote.tsx
> +        }
음... 그 부분은 조금 고민해봐야할 것 같아요.
request 과정 중에 interceptor를 사용하는 것은 봤는데, response에서 하는 것은 잘 못봐가지고요.
하지만 느낌상 response에서 interceptor 를 사용하면 가능할 것 같아요!
혹은 에러바운더리를 도입해도 괜찮을 것 같구요.
일단, 에러바운더리를 도입하기 위해서는 조금의 리소스가 드니 여기서는 response과정에서 한번 예외처리를 해보시죠.

2024-05-06 13:09 UTC, merged